Algoritmo "semnome"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Maju
// Data atual  : 13/02/2026
Var
// Seção de Declarações das variáveis 
         nome:caracter

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
      escreva("Digite seu nome completo:")
      leia(nome)
      escreva("Olá " , nome , " seja bem-vindo(a)!")

Fimalgoritmo