Algoritmo "sete"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : maju
// Data atual  : 13/02/2026
Var
// Seção de Declarações das variáveis 
        num, resto: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
           escreva("Digite um numero:")
           leia (num)
           
           escreva()
           resto <- num mod 2
           escreva ("O resto da divisão é:" , resto)

Fimalgoritmo