Algoritmo "21. Contagem Crescente"
// Disciplina  : Lógica de Programação
// Professor   : André Olímpio 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 23/02/2026
Var
// Seção de Declarações das variáveis 
    contador: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
  para contador de 1 ate 50 faca
      escreva(contador)
   fimpara

Fimalgoritmo